---
settings:
  name: Azure Blob storage
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Azure Blb存储文档
    url: "/index.html"
  - title: 发行说明
    url: "/whats-new.html"
  - title: 入门
    entries:
    - title: 查看您的Azure Blb存储帐户
      url: "/task-view-azure-blob-storage.html"
  - title: 管理Azure Blb存储帐户
    entries:
    - title: 添加新存储帐户
      url: "/task-add-blob-storage.html"
    - title: 更改存储帐户设置
      url: "/task-change-blob-storage-settings.html"
    - title: 将NetApp数据服务与Azure Blb存储结合使用
      url: "/task-blob-enable-data-services.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/task-support-registration.html"
    - title: 获取帮助
      url: "/task-get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 查看您的Azure Blb存储帐户
      url: task-view-azure-blob-storage.html
  - title: 管理Azure Blb存储帐户
    links:
    - title: 添加Blb存储帐户
      url: task-add-blob-storage.html
    - title: 更改存储帐户设置
      url: task-change-blob-storage-settings.html
    - title: 将NetApp数据服务与Azure Blb存储结合使用
      url: task-blob-enable-data-services.html
  - title: 更多信息
    links:
    - title: 用于在BlueXP之外进行管理的Azure Blb存储文档
      url: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction
  - title: 博客和社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: BlueXP博客
      url: https://bluexp.netapp.com/blog/topic/cloud-manager
    - title: BlueXP网络研讨会
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
